<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse mt-5');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
</div>

<div class="row">
<?php $this->trigger('view.browse.before'); ?> 
    
            <?php
            $headingTerm = $this->siteSetting('browse_heading_property_term');
            $bodyTerm = $this->siteSetting('browse_body_property_term');
            foreach ($itemSets as $itemSet) :
                $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle();
                $body = $bodyTerm ? $itemSet->value($bodyTerm) : $itemSet->displayDescription();
                if ($media = $itemSet->primaryMedia())
                $thumbnail = $media->thumbnailUrl('medium');
        
            $thumbnail = $itemSet->thumbnail();
            ?>
         <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="card" style="width: 18rem;">
    
            <a href="<?=$itemSet->url()?>">
            <img class="resource-list img-fluid" width="400px" src="<?= ($thumbnail->assetUrl()) ?>">
            </a>
            <div class="card-body">
       
            <?php if ($heading) : ?>
                <h5 class="card-title">
               <?php echo $itemSet->link($heading); ?>
               </h5>
            <?php endif; ?>
        <?php echo $body; ?>
        
            
            </div>
      </div>
      </div>
    <?php endforeach; ?>
   
    </div>
    <?php $this->trigger('view.browse.after'); ?>
    <?php echo $this->pagination(); ?>