<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse mt-5');
?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
</div>

<?php $this->trigger('view.browse.before'); ?> <table class="table">
    <thead>
        <tr>
            <th scope="col">Thumbnail</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>


        </tr>
    </thead>
    <tbody>
        <tr class="resource-list m-5">
            <?php
            $headingTerm = $this->siteSetting('browse_heading_property_term');
            $bodyTerm = $this->siteSetting('browse_body_property_term');
            foreach ($itemSets as $itemSet) :
                $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle();
                $body = $bodyTerm ? $itemSet->value($bodyTerm) : $itemSet->displayDescription();
                if ($media = $itemSet->primaryMedia())
                $thumbnail = $media->thumbnailUrl('medium');
        
            $thumbnail = $itemSet->thumbnail();
            ?>
        <tr class="item-set resource">
            <td class="col-3">
            <img class="resource-list img-fluid" width="400px" src="<?= ($thumbnail->assetUrl()) ?>">
            </td>

            <td class="col-3"><?php echo $itemSet->link($heading); ?></td>
            <?php if ($body) : ?>
                <td class="description"><?php echo $body; ?></td>
            <?php endif; ?>
            </td>
            <td class="col-3"><?php echo $itemSet->link($heading); ?></td>
            <?php if ($body) : ?>
                <td class="description"><?php echo $body; ?></td>
            <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    </table>
    
    <?php $this->trigger('view.browse.after'); ?>
    <?php echo $this->pagination(); ?>